services:
  - type: web
    name: chaatme-backend
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run db:migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: FRONTEND_URL
        value: https://chaatme-frontend.netlify.app
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_FROM
        value: ChaatMe <no-reply@chaatme.com>
    healthCheckPath: /health

databases:
  - name: chaatme-db
    databaseName: chaatme_prod
    user: chaatme_user
    plan: starter 